### ISSUE TITLE
Версия для Linux не запускается

### ISSUE THREAD

**Issue by hachikoharuno** [CrazyXacker/AniLabX-Lite-Desktop#6]
Здравствуйте, запускал программу на ubuntu 21.04, ubuntu 21.10, kde neon, сейчас использую arch. При запуске в err.txt следующая информация:

Unable to load app.properties
Dec 07, 2021 10:20:42 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4987985a'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:245)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:262)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:661)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:681)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 3 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:274)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:661)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:681)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

Погуглив ничего не нашел конкретного. Open jdk java 11 и 17 установлены.

**Comment by CrazyXacker** [comment]
Исправлено. https://github.com/CrazyXacker/AniLabX-Lite-Desktop/releases/tag/v1.6_linux_fix
